class OrderType:
    CALL='CALL'
    PUT='PUT'
    BUY='BUY'
    SELL='SELL'
class AlertType:
    RSI_OVERBOUGHT = "RSI_OVERBOUGHT"
    RSI_OVERSOLD = "RSI_OVERSOLD"
    MACD_SIGNAL_CROSS_MACD ='MACD_SIGNAL_CROSS_MACD'
    MACD_MACD_CROSS_SIGNAL = 'MACD_MACD_CROSS_SIGNAL'
    SMA_CONFIRMATION_UPWARD = 'SMA_CONFIRMATION_UPWARD'
    SMA_CONFIRMATION_DOWNWARD = 'SMA_CONFIRMATION_DOWNWARD'
    DMIPLUS_CROSSOVER_DMINEG= 'DMIPLUS_CROSSOVER_DMINEG'
    DMINEG_CROSSOVER_DMIPLUS = 'DMINEG_CROSSOVER_DMIPLUS'
    ADX_THRESHOLD_UPWARD = 'ADX_THRESHOLD_UPWARD'
    GOLDEN_CROSS_APPEARED = 'GOLDEN_CROSS_APPEARED'
    DEATH_CROSS_APPEARED = 'DEATH_CROSS_APPEARED'
    SR_CONSOLIDATING = 'SR_CONSOLIDATING'
    BREAKOUT_SR_UP = 'BREAKOUT_SR_UP'
    BREAKOUT_SR_DOWN = 'BREAKOUT_SR_DOWN'
    ABOVE_HIGHEST_SR_BAND = 'ABOVE_HIGHEST_SR_BAND'
    BELOW_LOWEST_SR_BAND = 'BELOW_LOWEST_SR_BAND'
    # ABOVE_UPPER_SR_BAND = 'ABOVE_UPPER_SR_BAND'
    # BELOW_LOWER_SR_BAND = 'BELOW_LOWER_SR_BAND'
class PositionType:
    LONG = "LONG"
    SHORT = "SHORT"
    SHORT_OPTION = "PUT"
    LONG_OPTION = "CALL"

class PriceGoalChangeType:
    ASSET_SET_PRICE = 'ASSET_SET_PRICE'
    ASSET_POINTS = 'ASSET_POINTS'
    ASSET_PERCENTAGE = 'ASSET_PERCENTAGE'
    OPTION_TICK = 'OPTION_TICK'
    OPTION_PERCENTAGE = 'OPTION_PERCENTAGE'
    OPTION_SET_PRICE = 'OPTION_SET_PRICE'

class Timespan:
    HOUR = "hour"
    MINUTE = "minute"
    DAY = "day"

class TimespanMultiplier:
    ONE = "1"
    FIFTEEN = "15"
    THIRTY = "30"

class ValidationType:
    SMA = 'sma'
    MACD = 'macd'
    DMI = 'dmi'
    ADX = 'adx'
    RSI = 'rsi'


validation_types = [
    ValidationType.ADX,
    ValidationType.DMI,
    ValidationType.RSI,
    ValidationType.SMA,
    ValidationType.MACD

]
position_types = [
    PositionType.LONG,
    PositionType.SHORT
]


alert_types=  [
    AlertType.RSI_OVERBOUGHT, AlertType.RSI_OVERSOLD, #rsi
    AlertType.SMA_CONFIRMATION_UPWARD, AlertType.SMA_CONFIRMATION_DOWNWARD, #sma
    AlertType.ADX_THRESHOLD_UPWARD, AlertType.DMINEG_CROSSOVER_DMIPLUS, AlertType.DMIPLUS_CROSSOVER_DMINEG, #adx, dmi
    AlertType.MACD_SIGNAL_CROSS_MACD, AlertType.MACD_MACD_CROSS_SIGNAL, #macd
    AlertType.BREAKOUT_SR_DOWN, AlertType.BREAKOUT_SR_UP, AlertType.SR_CONSOLIDATING, AlertType.BELOW_LOWEST_SR_BAND, AlertType.ABOVE_HIGHEST_SR_BAND, #sr bands
    AlertType.GOLDEN_CROSS_APPEARED, AlertType.DEATH_CROSS_APPEARED #crosses


]